import Head from "next/head";
import { Container } from "@chakra-ui/react";
import Navbar from "./Navbar";

export default function Layout(props) {
  const { children } = props;
  return (
    <Container
      maxW={{
        sm: "container.sm",
        md: "container.md",
        lg: "container.lg",
        xl: "container.xl",
      }}
    >
      <Head>
        <title>Phonepedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>{children}</div>
    </Container>
  );
}
